"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SELENIUM_DRIVER_PATH_FF = BASE_DIR / "var" / "selenium" / "geckodriver"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4!6ad7ullhv&z=14eab9=uj&4w9tk(zmrzp#r#$@*p68k)%x0r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"] #доступ ко всем

if DEBUG:
    INTERNAL_IPS = [
        "172.24.14.148",  #внутренний IP
        "127.0.0.1",  # кольцевой IP/локальный-может быть на удаленный
    ]
#INTERNAL_IPS = [
#        "127.0.0.1",] # кольцевой IP/локальный-может быть на удаленный

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mainapp',
    'authapp',
    'social_django',
    'crispy_forms',
    'markdownify.apps.MarkdownifyConfig',
    'debug_toolbar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates"
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',
                #'mainapp.context_processors.example.simple_context_processor',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
#WSGI_APPLICATION = 'mainapp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "authapp.CustomUser"

AUTHENTICATION_BACKENDS = (
    "social_core.backends.github.GithubOAuth2",
    "django.contrib.auth.backends.ModelBackend",
)


LOGIN_REDIRECT_URL = "mainapp:main"
LOGOUT_REDIRECT_URL = "mainapp:main"

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True  # Django будет отображать числа и даты, используя формат текущей локали.

USE_TZ = True  # datetimes будет учитывать часовой пояс.


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files
MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

#OAutn
SOCIAL_AUTH_GITHUB_KEY = "a162dda7a1d12ac58844"
SOCIAL_AUTH_GITHUB_SECRET = "10904ede3d0094054743616cc4b2c78cd219e5ae"

CRISPY_TEMPLATE_PACK = "bootstrap4"

LOG_FILE = BASE_DIR / "var" / "log" / "main_log.log"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False, #не отключаем существующие логгеры
    "formatters": {
        "console": { #имя
            "format": "[%(asctime)s] %(levelname)s %(name)s (%(lineno)d) %(message)s"
        },
    },
    "handlers": { #обработчик
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler", #поведение логгера
            "filename": LOG_FILE,
            "formatter": "console",
        },
        "console": {"class": "logging.StreamHandler", "formatter": "console"},
    },
    "loggers": {
        "django": {"level": "INFO", "handlers": ["console"]},
        "mainapp": {
            "level": "DEBUG",  # уровень от debug и выше
            "handlers": ["file", "console"],
        }
    },
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379", #прописывается протокол redis
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

CELERY_BROKER_URL = "redis://localhost:6379"  #указание на брокер
CELERY_RESULT_BACKEND = "redis://localhost:6379"  #указание бэкенда для результатов выполнения задач

# Read about sending email:
#   https://docs.djangoproject.com/en/3.2/topics/email/
# Full list of email settings:
#   https://docs.djangoproject.com/en/3.2/ref/settings/#email
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = 587
#DEFAULT_FROM_EMAIL = "kundasl1@gmail.com"
# For debugging: python -m smtpd -n -c DebuggingServer localhost:25
#EMAIL_HOST_USER = "kundasl1@gmail.com"
#EMAIL_HOST_PASSWORD = ""
#EMAIL_USE_SSL = False
# If server support TLS:
#EMAIL_USE_TLS = True
# Email as files for debug
#EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
#EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
#EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"
EMAIL_FILE_PATH = BASE_DIR / "var" / "email-messages"

LOCALE_PATHS = [BASE_DIR / "locale"]

#EMAIL_FILE_PATH = BASE_DIR / "var" / "email-messages" /
